<?xml version="1.0" encoding="utf-8" standalone="no"?>
<!--This file represents the results of running a test suite-->
<test-results name="C:\Users\bbdnet0518\Documents\GitHub\vodatest\bin\Debug\TestProj.dll" total="66" errors="14" failures="45" not-run="0" inconclusive="0" ignored="0" skipped="0" invalid="0" date="2014-12-02" time="12:40:57">
  <environment nunit-version="2.6.3.13283" clr-version="2.0.50727.8000" os-version="Microsoft Windows NT 6.2.9200.0" platform="Win32NT" cwd="C:\Program Files (x86)\NUnit 2.6.3\bin" machine-name="TONYV" user="bbdnet0518" user-domain="BBDNET" />
  <culture-info current-culture="en-ZA" current-uiculture="en-US" />
  <test-suite type="Assembly" name="C:\Users\bbdnet0518\Documents\GitHub\vodatest\bin\Debug\TestProj.dll" executed="True" result="Failure" success="False" time="157.277" asserts="0">
    <results>
      <test-suite type="Namespace" name="TestProj" executed="True" result="Failure" success="False" time="157.276" asserts="0">
        <results>
          <test-suite type="Namespace" name="Tests" executed="True" result="Failure" success="False" time="157.275" asserts="0">
            <results>
              <test-suite type="Namespace" name="AccessingApplication" executed="True" result="Failure" success="False" time="99.191" asserts="0">
                <results>
                  <test-suite type="TestFixture" name="AccessingApplication" description="AccessingApplication" executed="True" result="Failure" success="False" time="99.189" asserts="0">
                    <categories>
                      <category name="AccessingApplication" />
                    </categories>
                    <results>
                      <test-case name="TestProj.Tests.AccessingApplication.AccessingApplication._01_ActivationLandingPage" description="_01_ActivationLandingPage" executed="True" result="Success" success="True" time="0.750" asserts="0">
                        <categories>
                          <category name="Accessing app" />
                        </categories>
                        <properties>
                          <property name="Repeat" value="1" />
                        </properties>
                      </test-case>
                      <test-case name="TestProj.Tests.AccessingApplication.AccessingApplication._02_ApplicationFieldValidation" description="_02_ApplicationFieldValidation" executed="True" result="Error" success="False" time="6.393" asserts="0">
                        <categories>
                          <category name="Accessing app" />
                        </categories>
                        <properties>
                          <property name="Repeat" value="1" />
                        </properties>
                        <failure>
                          <message><![CDATA[FluentAutomation.Exceptions.FluentException : Conditional wait passed the timeout [5000ms] for expression [ => Invoke(value(FluentAutomation.BaseCommandProvider+<>c__DisplayClass0).action)]. See InnerException for details of the last FluentException thrown.
  ----> FluentAutomation.Exceptions.FluentAssertFailedException : Expected expression [ => ("07@" == value(TestProj.Tests.Common.Helpers+<>c__DisplayClass0).fieldProxy.Element.Text)] to return false.]]></message>
                          <stack-trace><![CDATA[at DynamicModule.ns.Wrapped_IAccessingApplicationActions_c6d15af0ff20491396df4f0dbbb88ba1.VerifyAlertSearchBox(Browser browserInstance)
at TestProj.Tests.AccessingApplication.AccessingApplication._02_ApplicationFieldValidation() in c:\Users\bbdnet0518\Documents\GitHub\vodatest\Tests\AccessingApplication\AccessingApplication.cs:line 247
--FluentAssertFailedException
at FluentAutomation.AssertProvider.ReportError(String message, Object[] formatParams)
at FluentAutomation.AssertProvider.<>c__DisplayClass62.<False>b__61()
at FluentAutomation.BaseCommandProvider.<>c__DisplayClass9.<WaitUntil>b__8()
]]></stack-trace>
                        </failure>
                      </test-case>
                      <test-case name="TestProj.Tests.AccessingApplication.AccessingApplication._03_ApplicationLandingContentsFunctionality" description="_03_ApplicationLandingContentsFunctionality" executed="True" result="Error" success="False" time="5.072" asserts="0">
                        <categories>
                          <category name="Accessing app" />
                        </categories>
                        <properties>
                          <property name="Repeat" value="1" />
                        </properties>
                        <failure>
                          <message><![CDATA[FluentAutomation.Exceptions.FluentException : Conditional wait passed the timeout [5000ms] for expression [ => Invoke(value(FluentAutomation.BaseCommandProvider+<>c__DisplayClass0).action)]. See InnerException for details of the last FluentException thrown.
  ----> FluentAutomation.Exceptions.FluentElementNotFoundException : Unable to find element with selector [#landingPage > div > div.leftBlock > div > div > div > div:nth-child(1) > div > div]]]></message>
                          <stack-trace><![CDATA[at DynamicModule.ns.Wrapped_IAccessingApplicationActions_c6d15af0ff20491396df4f0dbbb88ba1.VerifySpecialAccessibility(Browser browserInstance)
at TestProj.Tests.AccessingApplication.AccessingApplication._03_ApplicationLandingContentsFunctionality() in c:\Users\bbdnet0518\Documents\GitHub\vodatest\Tests\AccessingApplication\AccessingApplication.cs:line 272
--FluentElementNotFoundException
at FluentAutomation.CommandProvider.<>c__DisplayClass8.<Find>b__7()
at FluentAutomation.ElementProxy.get_Element()
at FluentAutomation.CommandProvider.<>c__DisplayClass18.<Click>b__17()
at FluentAutomation.BaseCommandProvider.<>c__DisplayClass9.<WaitUntil>b__8()
]]></stack-trace>
                        </failure>
                      </test-case>
                      <test-case name="TestProj.Tests.AccessingApplication.AccessingApplication._04_ApplicationWithMultipleSpazas" description="_04_ApplicationWithMultipleSpazas" executed="True" result="Error" success="False" time="5.326" asserts="0">
                        <categories>
                          <category name="Accessing app" />
                        </categories>
                        <properties>
                          <property name="Repeat" value="1" />
                        </properties>
                        <failure>
                          <message><![CDATA[FluentAutomation.Exceptions.FluentException : Conditional wait passed the timeout [5000ms] for expression [ => Invoke(value(FluentAutomation.BaseCommandProvider+<>c__DisplayClass0).action)]. See InnerException for details of the last FluentException thrown.
  ----> FluentAutomation.Exceptions.FluentElementNotFoundException : Unable to find element with selector [#landingPage > div > div.leftBlock > div > div > div > div:nth-child(1) > div > div]]]></message>
                          <stack-trace><![CDATA[at FluentAutomation.BaseCommandProvider.<>c__DisplayClass9.<WaitUntil>b__8()
at FluentAutomation.BaseCommandProvider.Act(CommandType commandType, Action action)
at FluentAutomation.BaseCommandProvider.WaitUntil(Expression`1 conditionAction, TimeSpan timeout)
at FluentAutomation.BaseCommandProvider.Act(CommandType commandType, Action action)
at FluentAutomation.CommandProvider.Click(ElementProxy element)
at FluentAutomation.ActionSyntaxProvider.Click(ElementProxy element)
at TestProj.Tests.Common.Helpers.ClickButton(Browser browserInstance, ElementProxy buttonProxy) in c:\Users\bbdnet0518\Documents\GitHub\vodatest\Tests\Common\Helpers.cs:line 64
at TestProj.Tests.AccessingApplication.AccessingApplication._04_ApplicationWithMultipleSpazas() in c:\Users\bbdnet0518\Documents\GitHub\vodatest\Tests\AccessingApplication\AccessingApplication.cs:line 318
--FluentElementNotFoundException
at FluentAutomation.CommandProvider.<>c__DisplayClass8.<Find>b__7()
at FluentAutomation.ElementProxy.get_Element()
at FluentAutomation.CommandProvider.<>c__DisplayClass18.<Click>b__17()
at FluentAutomation.BaseCommandProvider.<>c__DisplayClass9.<WaitUntil>b__8()
]]></stack-trace>
                        </failure>
                      </test-case>
                      <test-case name="TestProj.Tests.AccessingApplication.AccessingApplication._05_AccessApplicationWithSingleSpaza" description="_05_AccessApplicationWithSingleSpaza" executed="True" result="Success" success="True" time="1.322" asserts="0">
                        <categories>
                          <category name="Accessing app" />
                        </categories>
                        <properties>
                          <property name="Repeat" value="1" />
                        </properties>
                      </test-case>
                    </results>
                  </test-suite>
                </results>
              </test-suite>
              <test-suite type="Namespace" name="Activation" executed="True" result="Failure" success="False" time="57.431" asserts="0">
                <results>
                  <test-suite type="TestFixture" name="Activation" description="Activation" executed="True" result="Failure" success="False" time="57.430" asserts="0">
                    <categories>
                      <category name="Activation" />
                    </categories>
                    <results>
                      <test-case name="TestProj.Tests.Activation.Activation._01_VerifyActivationLandingPage" description="_01_VerifyActivationLandingPage" executed="True" result="Success" success="True" time="4.306" asserts="0">
                        <categories>
                          <category name="Activation Page" />
                        </categories>
                        <properties>
                          <property name="Repeat" value="1" />
                        </properties>
                      </test-case>
                      <test-case name="TestProj.Tests.Activation.Activation._02_ActivationFormFieldValidation" description="_02_ActivationFormFieldValidation" executed="True" result="Error" success="False" time="5.302" asserts="0">
                        <categories>
                          <category name="Activation Page" />
                        </categories>
                        <properties>
                          <property name="Repeat" value="1" />
                        </properties>
                        <failure>
                          <message><![CDATA[FluentAutomation.Exceptions.FluentException : Conditional wait passed the timeout [5000ms] for expression [ => Invoke(value(FluentAutomation.BaseCommandProvider+<>c__DisplayClass0).action)]. See InnerException for details of the last FluentException thrown.
  ----> FluentAutomation.Exceptions.FluentAssertFailedException : Expected expression [ => ("E1-1-7 – Please complete all fields" == value(TestProj.Tests.Activation.ActivationActions+<>c__DisplayClass6).errorMessage.Element.Text)] to return true.]]></message>
                          <stack-trace><![CDATA[at DynamicModule.ns.Wrapped_IActivationActions_0ab4a0c158e1444580b1e1098c4c8f6f.TestMandatoryFields(Browser browserInstance, ElementProxy msisdn, ElementProxy username, ElementProxy activationNumber, ElementProxy userAlias, ElementProxy challengeQuestion, ElementProxy challengeAnswer, ElementProxy errorMessage)
at TestProj.Tests.Activation.Activation._02_ActivationFormFieldValidation() in c:\Users\bbdnet0518\Documents\GitHub\vodatest\Tests\Activation\Activation.cs:line 189
--FluentAssertFailedException
at FluentAutomation.AssertProvider.ReportError(String message, Object[] formatParams)
at FluentAutomation.AssertProvider.<>c__DisplayClass5f.<True>b__5e()
at FluentAutomation.BaseCommandProvider.<>c__DisplayClass9.<WaitUntil>b__8()
]]></stack-trace>
                        </failure>
                      </test-case>
                      <test-case name="TestProj.Tests.Activation.Activation._03_ActivationFormIncorrectUserDetails" description="_03_ActivationFormIncorrectUserDetails" executed="True" result="Error" success="False" time="6.252" asserts="0">
                        <categories>
                          <category name="Activation form" />
                        </categories>
                        <properties>
                          <property name="Repeat" value="1" />
                        </properties>
                        <failure>
                          <message><![CDATA[FluentAutomation.Exceptions.FluentException : Conditional wait passed the timeout [5000ms] for expression [ => Invoke(value(FluentAutomation.BaseCommandProvider+<>c__DisplayClass0).action)]. See InnerException for details of the last FluentException thrown.
  ----> FluentAutomation.Exceptions.FluentAssertFailedException : Expected expression [ => ("E1-1 -3 invalid input" == value(TestProj.Tests.Activation.ActivationActions+<>c__DisplayClasse).errorMessage.Element.Text)] to return true.]]></message>
                          <stack-trace><![CDATA[at DynamicModule.ns.Wrapped_IActivationActions_0ab4a0c158e1444580b1e1098c4c8f6f.TestInvalidActivationKey(Browser browserInstance, ElementProxy msisdn, ElementProxy username, ElementProxy activationNumber, ElementProxy userAlias, ElementProxy nextButton, ElementProxy errorMessage)
at TestProj.Tests.Activation.Activation._03_ActivationFormIncorrectUserDetails() in c:\Users\bbdnet0518\Documents\GitHub\vodatest\Tests\Activation\Activation.cs:line 237
--FluentAssertFailedException
at FluentAutomation.AssertProvider.ReportError(String message, Object[] formatParams)
at FluentAutomation.AssertProvider.<>c__DisplayClass5f.<True>b__5e()
at FluentAutomation.BaseCommandProvider.<>c__DisplayClass9.<WaitUntil>b__8()
]]></stack-trace>
                        </failure>
                      </test-case>
                      <test-case name="TestProj.Tests.Activation.Activation._04_ActivationFormCorrectUserDetails" description="_04_ActivationFormCorrectUserDetails" executed="True" result="Error" success="False" time="7.109" asserts="0">
                        <categories>
                          <category name="Activation form" />
                        </categories>
                        <properties>
                          <property name="Repeat" value="1" />
                        </properties>
                        <failure>
                          <message><![CDATA[FluentAutomation.Exceptions.FluentException : Conditional wait passed the timeout [5000ms] for expression [ => Invoke(value(FluentAutomation.BaseCommandProvider+<>c__DisplayClass0).action)]. See InnerException for details of the last FluentException thrown.
  ----> FluentAutomation.Exceptions.FluentAssertFailedException : Expected expression [ => (value(TestProj.Tests.Activation.ActivationActions+<>c__DisplayClass10).message == value(TestProj.Tests.Activation.ActivationActions+<>c__DisplayClass10).otpMessage.Element.Text)] to return true.]]></message>
                          <stack-trace><![CDATA[at DynamicModule.ns.Wrapped_IActivationActions_0ab4a0c158e1444580b1e1098c4c8f6f.ValidateOTPStart(Browser browserInstance, String msisdnNo)
at TestProj.Tests.Activation.Activation._04_ActivationFormCorrectUserDetails() in c:\Users\bbdnet0518\Documents\GitHub\vodatest\Tests\Activation\Activation.cs:line 280
--FluentAssertFailedException
at FluentAutomation.AssertProvider.ReportError(String message, Object[] formatParams)
at FluentAutomation.AssertProvider.<>c__DisplayClass5f.<True>b__5e()
at FluentAutomation.BaseCommandProvider.<>c__DisplayClass9.<WaitUntil>b__8()
]]></stack-trace>
                        </failure>
                      </test-case>
                      <test-case name="TestProj.Tests.Activation.Activation._05_VerifyActivationOneTimePinLandingPage" description="_05_VerifyActivationOneTimePinLandingPage" executed="True" result="Error" success="False" time="5.996" asserts="0">
                        <categories>
                          <category name="Activation_form" />
                        </categories>
                        <properties>
                          <property name="Repeat" value="1" />
                        </properties>
                        <failure>
                          <message><![CDATA[FluentAutomation.Exceptions.FluentException : Conditional wait passed the timeout [5000ms] for expression [ => Invoke(value(FluentAutomation.BaseCommandProvider+<>c__DisplayClass0).action)]. See InnerException for details of the last FluentException thrown.
  ----> FluentAutomation.Exceptions.FluentAssertFailedException : Expected expression [ => (value(TestProj.Tests.Activation.ActivationActions+<>c__DisplayClass10).message == value(TestProj.Tests.Activation.ActivationActions+<>c__DisplayClass10).otpMessage.Element.Text)] to return true.]]></message>
                          <stack-trace><![CDATA[at DynamicModule.ns.Wrapped_IActivationActions_0ab4a0c158e1444580b1e1098c4c8f6f.VerifyOTPErrorMessage(Browser browserInstance, String msisdnNo)
at TestProj.Tests.Activation.Activation._05_VerifyActivationOneTimePinLandingPage() in c:\Users\bbdnet0518\Documents\GitHub\vodatest\Tests\Activation\Activation.cs:line 338
--FluentAssertFailedException
at FluentAutomation.AssertProvider.ReportError(String message, Object[] formatParams)
at FluentAutomation.AssertProvider.<>c__DisplayClass5f.<True>b__5e()
at FluentAutomation.BaseCommandProvider.<>c__DisplayClass9.<WaitUntil>b__8()
]]></stack-trace>
                        </failure>
                      </test-case>
                      <test-case name="TestProj.Tests.Activation.Activation._06_ActivationOneTimePinFieldValidation" description="_06_ActivationOneTimePinFieldValidation" executed="True" result="Success" success="True" time="0.002" asserts="0">
                        <categories>
                          <category name="Verify_user(OTP)" />
                        </categories>
                        <properties>
                          <property name="Repeat" value="1" />
                        </properties>
                      </test-case>
                      <test-case name="TestProj.Tests.Activation.Activation._07_CorrectOneTimePinAndApplicationOffline" description="_07_CorrectOneTimePinAndApplicationOffline" executed="True" result="Error" success="False" time="5.012" asserts="0">
                        <categories>
                          <category name="Verify_user(OTP)" />
                        </categories>
                        <properties>
                          <property name="Repeat" value="1" />
                        </properties>
                        <failure>
                          <message><![CDATA[FluentAutomation.Exceptions.FluentException : Conditional wait passed the timeout [5000ms] for expression [ => Invoke(value(FluentAutomation.BaseCommandProvider+<>c__DisplayClass0).action)]. See InnerException for details of the last FluentException thrown.
  ----> FluentAutomation.Exceptions.FluentAssertFailedException : Expected element [body > div:nth-child(1) > div > div > ng-include > div > div > div.statusElements.left > div.topRow > div > div] to include CSS class [offline] but current class attribute is [statusDisplay online ng-binding].]]></message>
                          <stack-trace><![CDATA[at FluentAutomation.BaseCommandProvider.<>c__DisplayClass9.<WaitUntil>b__8()
at FluentAutomation.BaseCommandProvider.Act(CommandType commandType, Action action)
at FluentAutomation.BaseCommandProvider.WaitUntil(Expression`1 conditionAction, TimeSpan timeout)
at FluentAutomation.BaseCommandProvider.Act(CommandType commandType, Action action)
at FluentAutomation.CommandProvider.FluentAutomation.Interfaces.ICommandProvider.Act(CommandType , Action )
at FluentAutomation.AssertProvider.CssClass(ElementProxy element, String className)
at FluentAutomation.AssertSyntaxProvider.AssertClassSyntaxProvider.On(ElementProxy element)
at TestProj.Tests.Activation.Activation._07_CorrectOneTimePinAndApplicationOffline() in c:\Users\bbdnet0518\Documents\GitHub\vodatest\Tests\Activation\Activation.cs:line 393
--FluentAssertFailedException
at FluentAutomation.AssertProvider.ReportError(String message, Object[] formatParams)
at FluentAutomation.AssertProvider.<>c__DisplayClass15.<CssClass>b__14()
at FluentAutomation.BaseCommandProvider.<>c__DisplayClass9.<WaitUntil>b__8()
]]></stack-trace>
                        </failure>
                      </test-case>
                      <test-case name="TestProj.Tests.Activation.Activation._08_IncorrectOneTimePin" description="_08_IncorrectOneTimePin" executed="True" result="Error" success="False" time="5.454" asserts="0">
                        <categories>
                          <category name="Verify_user(OTP)" />
                        </categories>
                        <properties>
                          <property name="Repeat" value="1" />
                        </properties>
                        <failure>
                          <message><![CDATA[FluentAutomation.Exceptions.FluentException : Conditional wait passed the timeout [5000ms] for expression [ => Invoke(value(FluentAutomation.BaseCommandProvider+<>c__DisplayClass0).action)]. See InnerException for details of the last FluentException thrown.
  ----> FluentAutomation.Exceptions.FluentAssertFailedException : Expected expression [ => (value(TestProj.Tests.Activation.Activation).otpErrorMessage.Element.Text == "O1-2-8 – Passwords do not match. Please try again")] to return true.]]></message>
                          <stack-trace><![CDATA[at FluentAutomation.BaseCommandProvider.<>c__DisplayClass9.<WaitUntil>b__8()
at FluentAutomation.BaseCommandProvider.Act(CommandType commandType, Action action)
at FluentAutomation.BaseCommandProvider.WaitUntil(Expression`1 conditionAction, TimeSpan timeout)
at FluentAutomation.BaseCommandProvider.Act(CommandType commandType, Action action)
at FluentAutomation.CommandProvider.FluentAutomation.Interfaces.ICommandProvider.Act(CommandType , Action )
at FluentAutomation.AssertProvider.True(Expression`1 matchFunc)
at FluentAutomation.AssertSyntaxProvider.True(Expression`1 matchFunc)
at TestProj.Tests.Activation.Activation._08_IncorrectOneTimePin() in c:\Users\bbdnet0518\Documents\GitHub\vodatest\Tests\Activation\Activation.cs:line 437
--FluentAssertFailedException
at FluentAutomation.AssertProvider.ReportError(String message, Object[] formatParams)
at FluentAutomation.AssertProvider.<>c__DisplayClass5f.<True>b__5e()
at FluentAutomation.BaseCommandProvider.<>c__DisplayClass9.<WaitUntil>b__8()
]]></stack-trace>
                        </failure>
                      </test-case>
                      <test-case name="TestProj.Tests.Activation.Activation._09_ResendOneTimePin" description="_09_ResendOneTimePin" executed="True" result="Error" success="False" time="5.218" asserts="0">
                        <categories>
                          <category name="Verify_user(OTP)" />
                        </categories>
                        <properties>
                          <property name="Repeat" value="1" />
                        </properties>
                        <failure>
                          <message><![CDATA[FluentAutomation.Exceptions.FluentException : Conditional wait passed the timeout [5000ms] for expression [ => Invoke(value(FluentAutomation.BaseCommandProvider+<>c__DisplayClass0).action)]. See InnerException for details of the last FluentException thrown.
  ----> FluentAutomation.Exceptions.FluentAssertFailedException : Expected expression [ => (value(TestProj.Tests.Activation.ActivationActions+<>c__DisplayClass10).message == value(TestProj.Tests.Activation.ActivationActions+<>c__DisplayClass10).otpMessage.Element.Text)] to return true.]]></message>
                          <stack-trace><![CDATA[at DynamicModule.ns.Wrapped_IActivationActions_0ab4a0c158e1444580b1e1098c4c8f6f.VerifyOTPErrorMessage(Browser browserInstance, String msisdnNo)
at TestProj.Tests.Activation.Activation._09_ResendOneTimePin() in c:\Users\bbdnet0518\Documents\GitHub\vodatest\Tests\Activation\Activation.cs:line 481
--FluentAssertFailedException
at FluentAutomation.AssertProvider.ReportError(String message, Object[] formatParams)
at FluentAutomation.AssertProvider.<>c__DisplayClass5f.<True>b__5e()
at FluentAutomation.BaseCommandProvider.<>c__DisplayClass9.<WaitUntil>b__8()
]]></stack-trace>
                        </failure>
                      </test-case>
                      <test-case name="TestProj.Tests.Activation.Activation._10_CorrectOneTimePin" description="_10_CorrectOneTimePin" executed="True" result="Error" success="False" time="0.219" asserts="0">
                        <categories>
                          <category name="Verify_user(OTP)" />
                        </categories>
                        <properties>
                          <property name="Repeat" value="1" />
                        </properties>
                        <failure>
                          <message><![CDATA[FluentAutomation.Exceptions.FluentException : An unexpected exception was thrown inside WaitUntil(Action). See InnerException for details.
  ----> System.InvalidOperationException : unknown error: cannot focus element
  (Session info: chrome=39.0.2171.71)
  (Driver info: chromedriver=2.9.248315,platform=Windows NT 6.3 x86_64)]]></message>
                          <stack-trace><![CDATA[at DynamicModule.ns.Wrapped_IActivationActions_0ab4a0c158e1444580b1e1098c4c8f6f.EnterAndVerifyOTPValue(Browser browserInstance, ElementProxy otp, String otpVal)
at TestProj.Tests.Activation.Activation._10_CorrectOneTimePin() in c:\Users\bbdnet0518\Documents\GitHub\vodatest\Tests\Activation\Activation.cs:line 517
--InvalidOperationException
at OpenQA.Selenium.Remote.RemoteWebDriver.UnpackAndThrowOnError(Response errorResponse)
at OpenQA.Selenium.Remote.RemoteWebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)
at FluentAutomation.CommandProvider.<>c__DisplayClass42.<EnterText>b__41()
at FluentAutomation.BaseCommandProvider.<>c__DisplayClass9.<WaitUntil>b__8()
]]></stack-trace>
                        </failure>
                      </test-case>
                      <test-case name="TestProj.Tests.Activation.Activation._11_SetupCatalogueLandingPage" description="_11_SetupCatalogueLandingPage" executed="True" result="Error" success="False" time="0.411" asserts="0">
                        <categories>
                          <category name="Setup_Catalogue" />
                        </categories>
                        <properties>
                          <property name="Repeat" value="1" />
                        </properties>
                        <failure>
                          <message><![CDATA[FluentAutomation.Exceptions.FluentException : An unexpected exception was thrown inside WaitUntil(Action). See InnerException for details.
  ----> OpenQA.Selenium.UnhandledAlertException : unexpected alert open
  (Session info: chrome=39.0.2171.71)
  (Driver info: chromedriver=2.9.248315,platform=Windows NT 6.3 x86_64)]]></message>
                          <stack-trace><![CDATA[at DynamicModule.ns.Wrapped_IActivationActions_0ab4a0c158e1444580b1e1098c4c8f6f.VerifyOnlineIndicator(Browser browserInstance)
at TestProj.Tests.Activation.Activation._11_SetupCatalogueLandingPage() in c:\Users\bbdnet0518\Documents\GitHub\vodatest\Tests\Activation\Activation.cs:line 567
--UnhandledAlertException
at OpenQA.Selenium.Remote.RemoteWebDriver.UnpackAndThrowOnError(Response errorResponse)
at OpenQA.Selenium.Remote.RemoteWebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)
at OpenQA.Selenium.Remote.RemoteWebElement.GetAttribute(String attributeName)
at FluentAutomation.ElementAttributeSelector.Get(String name)
at FluentAutomation.AssertProvider.elementHasClass(ElementProxy element, String className)
at FluentAutomation.AssertProvider.<>c__DisplayClass15.<CssClass>b__14()
at FluentAutomation.BaseCommandProvider.<>c__DisplayClass9.<WaitUntil>b__8()
]]></stack-trace>
                        </failure>
                      </test-case>
                      <test-case name="TestProj.Tests.Activation.Activation._12_SetupCatalogueValidations" description="_12_SetupCatalogueValidations" executed="True" result="Error" success="False" time="5.051" asserts="0">
                        <categories>
                          <category name="Setup_Catalogue" />
                        </categories>
                        <properties>
                          <property name="Repeat" value="1" />
                        </properties>
                        <failure>
                          <message><![CDATA[FluentAutomation.Exceptions.FluentException : Conditional wait passed the timeout [5000ms] for expression [ => Invoke(value(FluentAutomation.BaseCommandProvider+<>c__DisplayClass0).action)]. See InnerException for details of the last FluentException thrown.
  ----> FluentAutomation.Exceptions.FluentException : An error ocurred while locating an element via jQuery/Sizzle. InnerException may have more details.
  ----> OpenQA.Selenium.UnhandledAlertException : unexpected alert open
  (Session info: chrome=39.0.2171.71)
  (Driver info: chromedriver=2.9.248315,platform=Windows NT 6.3 x86_64)]]></message>
                          <stack-trace><![CDATA[at DynamicModule.ns.Wrapped_IActivationActions_0ab4a0c158e1444580b1e1098c4c8f6f.TestCatalogueSeachValidation(Browser browserInstance, ElementProxy searchValue, ElementProxy mcatSearchButton, ElementProxy mcatErrorMessage)
at TestProj.Tests.Activation.Activation._12_SetupCatalogueValidations() in c:\Users\bbdnet0518\Documents\GitHub\vodatest\Tests\Activation\Activation.cs:line 618
--FluentException
at FluentAutomation.Sizzle.BySizzle.FindElements(ISearchContext context)
at FluentAutomation.Sizzle.BySizzle.FindElement(ISearchContext context)
at FluentAutomation.CommandProvider.<>c__DisplayClass8.<Find>b__7()
at FluentAutomation.ElementProxy.get_Element()
at FluentAutomation.CommandProvider.<>c__DisplayClass18.<Click>b__17()
at FluentAutomation.BaseCommandProvider.<>c__DisplayClass9.<WaitUntil>b__8()
--UnhandledAlertException
at OpenQA.Selenium.Remote.RemoteWebDriver.UnpackAndThrowOnError(Response errorResponse)
at OpenQA.Selenium.Remote.RemoteWebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)
at OpenQA.Selenium.Remote.RemoteWebDriver.ExecuteScriptCommand(String script, String commandName, Object[] args)
at FluentAutomation.Sizzle.BySizzle.FindElements(ISearchContext context)
]]></stack-trace>
                        </failure>
                      </test-case>
                      <test-case name="TestProj.Tests.Activation.Activation._14_SetupCatalogueSearchFieldReturningNoResults" description="_14_SetupCatalogueSearchFieldReturningNoResults" executed="True" result="Error" success="False" time="0.010" asserts="0">
                        <categories>
                          <category name="Setup_Catalogue" />
                        </categories>
                        <properties>
                          <property name="Repeat" value="1" />
                        </properties>
                        <failure>
                          <message><![CDATA[FluentAutomation.Exceptions.FluentException : An unexpected exception was thrown inside WaitUntil(Action). See InnerException for details.
  ----> OpenQA.Selenium.UnhandledAlertException : unexpected alert open
  (Session info: chrome=39.0.2171.71)
  (Driver info: chromedriver=2.9.248315,platform=Windows NT 6.3 x86_64)]]></message>
                          <stack-trace><![CDATA[at FluentAutomation.BaseCommandProvider.<>c__DisplayClass9.<WaitUntil>b__8()
at FluentAutomation.BaseCommandProvider.Act(CommandType commandType, Action action)
at FluentAutomation.BaseCommandProvider.WaitUntil(Expression`1 conditionAction, TimeSpan timeout)
at FluentAutomation.BaseCommandProvider.Act(CommandType commandType, Action action)
at FluentAutomation.CommandProvider.Navigate(Uri url)
at FluentAutomation.ActionSyntaxProvider.Open(Uri url)
at FluentAutomation.ActionSyntaxProvider.Open(String url)
at TestProj.Classes.Browser.Navigate(Uri path) in c:\Users\bbdnet0518\Documents\GitHub\vodatest\Classes\Browser.cs:line 62
at TestProj.Tests.Activation.Activation._14_SetupCatalogueSearchFieldReturningNoResults() in c:\Users\bbdnet0518\Documents\GitHub\vodatest\Tests\Activation\Activation.cs:line 637
--UnhandledAlertException
at OpenQA.Selenium.Remote.RemoteWebDriver.UnpackAndThrowOnError(Response errorResponse)
at OpenQA.Selenium.Remote.RemoteWebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)
at OpenQA.Selenium.Remote.RemoteWebDriver.get_Url()
at FluentAutomation.CommandProvider.<>c__DisplayClass5.<Navigate>b__4()
at FluentAutomation.BaseCommandProvider.<>c__DisplayClass9.<WaitUntil>b__8()
]]></stack-trace>
                        </failure>
                      </test-case>
                      <test-case name="TestProj.Tests.Activation.Activation._15_SetupCatalogueSearchFieldFilter" description="_15_SetupCatalogueSearchFieldFilter" executed="True" result="Success" success="True" time="0.002" asserts="0">
                        <categories>
                          <category name="Setup_Catalogue" />
                        </categories>
                        <properties>
                          <property name="Repeat" value="1" />
                        </properties>
                      </test-case>
                      <test-case name="TestProj.Tests.Activation.Activation._16_SetupCatalogueLandingPageInterruptions" description="_16_SetupCatalogueLandingPageInterruptions" executed="True" result="Success" success="True" time="0.002" asserts="0">
                        <categories>
                          <category name="Setup_Catalogue" />
                        </categories>
                        <properties>
                          <property name="Repeat" value="1" />
                        </properties>
                      </test-case>
                      <test-case name="TestProj.Tests.Activation.Activation._17_SetupCatalogueSearchFieldReturningOneOrMultipleResults" description="_17_SetupCatalogueSearchFieldReturningOneOrMultipleResults" executed="True" result="Success" success="True" time="0.002" asserts="0">
                        <categories>
                          <category name="Setup_Catalogue" />
                        </categories>
                        <properties>
                          <property name="Repeat" value="1" />
                        </properties>
                      </test-case>
                    </results>
                  </test-suite>
                </results>
              </test-suite>
              <test-suite type="Namespace" name="Alerts" executed="True" result="Failure" success="False" time="0.094" asserts="0">
                <results>
                  <test-suite type="TestFixture" name="Alerts" description="Alerts" executed="True" result="Error" success="False" time="0.092" asserts="0">
                    <categories>
                      <category name="Alerts" />
                    </categories>
                    <failure>
                      <message><![CDATA[SetUp : System.IO.IOException : The process cannot access the file 'C:\Users\bbdnet0518\AppData\Local\Temp\chromedriver.exe' because it is being used by another process.]]></message>
                      <stack-trace><![CDATA[at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
at System.IO.File.InternalWriteAllBytes(String path, Byte[] bytes, Boolean checkHost)
at FluentAutomation.EmbeddedResources.UnpackFromAssembly(String resourceFileName, String outputFileName, Assembly assembly)
at FluentAutomation.EmbeddedResources.UnpackFromAssembly(String resourceFileName, Assembly assembly)
at FluentAutomation.SeleniumWebDriver.GenerateBrowserSpecificDriver(Browser browser, TimeSpan commandTimeout)
at FluentAutomation.SeleniumWebDriver.<>c__DisplayClass2.<Bootstrap>b__0(TinyIoCContainer container)
at FluentAutomation.FluentSession.BootstrapTypeRegistration(Action`1 containerAction)
at FluentAutomation.FluentTest.get_I()
at TestProj.Classes.Browsers.Chrome.Create() in c:\Users\bbdnet0518\Documents\GitHub\vodatest\Classes\Browsers\Chrome.cs:line 18
at TestProj.Classes.Browser..ctor(eBrowser browserType) in c:\Users\bbdnet0518\Documents\GitHub\vodatest\Classes\Browser.cs:line 44
at TestProj.Tests.Alerts.Alerts.Initialise() in c:\Users\bbdnet0518\Documents\GitHub\vodatest\Tests\Alerts\Alerts.cs:line 21
]]></stack-trace>
                    </failure>
                    <results>
                      <test-case name="TestProj.Tests.Alerts.Alerts._01_AlertsLandingPageVerfication" description="_01_AlertsLandingPageVerfication" executed="True" result="Failure" success="False" time="0.000" asserts="0">
                        <categories>
                          <category name="Alerts" />
                        </categories>
                        <properties>
                          <property name="Repeat" value="1" />
                        </properties>
                        <failure>
                          <message><![CDATA[TestFixtureSetUp failed in Alerts]]></message>
                          <stack-trace />
                        </failure>
                      </test-case>
                      <test-case name="TestProj.Tests.Alerts.Alerts._02_AlertsPollingService" description="_02_AlertsPollingService" executed="True" result="Failure" success="False" time="0.000" asserts="0">
                        <categories>
                          <category name="Alerts" />
                        </categories>
                        <properties>
                          <property name="Repeat" value="1" />
                        </properties>
                        <failure>
                          <message><![CDATA[TestFixtureSetUp failed in Alerts]]></message>
                          <stack-trace />
                        </failure>
                      </test-case>
                      <test-case name="TestProj.Tests.Alerts.Alerts._03_AlertsViewInvoices" description="_03_AlertsViewInvoices" executed="True" result="Failure" success="False" time="0.000" asserts="0">
                        <categories>
                          <category name="Alerts" />
                        </categories>
                        <properties>
                          <property name="Repeat" value="1" />
                        </properties>
                        <failure>
                          <message><![CDATA[TestFixtureSetUp failed in Alerts]]></message>
                          <stack-trace />
                        </failure>
                      </test-case>
                      <test-case name="TestProj.Tests.Alerts.Alerts._04_AlertsConfirmNow" description="_04_AlertsConfirmNow" executed="True" result="Failure" success="False" time="0.000" asserts="0">
                        <categories>
                          <category name="Alerts" />
                        </categories>
                        <properties>
                          <property name="Repeat" value="1" />
                        </properties>
                        <failure>
                          <message><![CDATA[TestFixtureSetUp failed in Alerts]]></message>
                          <stack-trace />
                        </failure>
                      </test-case>
                      <test-case name="TestProj.Tests.Alerts.Alerts._05_AlertsSyncNow" description="_05_AlertsSyncNow" executed="True" result="Failure" success="False" time="0.000" asserts="0">
                        <categories>
                          <category name="Alerts" />
                        </categories>
                        <properties>
                          <property name="Repeat" value="1" />
                        </properties>
                        <failure>
                          <message><![CDATA[TestFixtureSetUp failed in Alerts]]></message>
                          <stack-trace />
                        </failure>
                      </test-case>
                      <test-case name="TestProj.Tests.Alerts.Alerts._06_AlertsManageCatalogue" description="_06_AlertsManageCatalogue" executed="True" result="Failure" success="False" time="0.000" asserts="0">
                        <categories>
                          <category name="Setup_Catalogue" />
                        </categories>
                        <properties>
                          <property name="Repeat" value="1" />
                        </properties>
                        <failure>
                          <message><![CDATA[TestFixtureSetUp failed in Alerts]]></message>
                          <stack-trace />
                        </failure>
                      </test-case>
                      <test-case name="TestProj.Tests.Alerts.Alerts._07_AlertsDiagnose" description="_07_AlertsDiagnose" executed="True" result="Failure" success="False" time="0.000" asserts="0">
                        <categories>
                          <category name="Alerts" />
                        </categories>
                        <properties>
                          <property name="Repeat" value="1" />
                        </properties>
                        <failure>
                          <message><![CDATA[TestFixtureSetUp failed in Alerts]]></message>
                          <stack-trace />
                        </failure>
                      </test-case>
                      <test-case name="TestProj.Tests.Alerts.Alerts._09_AlertsMessaging" description="_09_AlertsMessaging" executed="True" result="Failure" success="False" time="0.000" asserts="0">
                        <categories>
                          <category name="Alerts" />
                        </categories>
                        <properties>
                          <property name="Repeat" value="1" />
                        </properties>
                        <failure>
                          <message><![CDATA[TestFixtureSetUp failed in Alerts]]></message>
                          <stack-trace />
                        </failure>
                      </test-case>
                    </results>
                  </test-suite>
                </results>
              </test-suite>
              <test-suite type="Namespace" name="Basket" executed="True" result="Failure" success="False" time="0.077" asserts="0">
                <results>
                  <test-suite type="TestFixture" name="Basket" description="Basket" executed="True" result="Error" success="False" time="0.075" asserts="0">
                    <categories>
                      <category name="Basket" />
                    </categories>
                    <failure>
                      <message><![CDATA[SetUp : System.IO.IOException : The process cannot access the file 'C:\Users\bbdnet0518\AppData\Local\Temp\chromedriver.exe' because it is being used by another process.]]></message>
                      <stack-trace><![CDATA[at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
at System.IO.File.InternalWriteAllBytes(String path, Byte[] bytes, Boolean checkHost)
at FluentAutomation.EmbeddedResources.UnpackFromAssembly(String resourceFileName, String outputFileName, Assembly assembly)
at FluentAutomation.EmbeddedResources.UnpackFromAssembly(String resourceFileName, Assembly assembly)
at FluentAutomation.SeleniumWebDriver.GenerateBrowserSpecificDriver(Browser browser, TimeSpan commandTimeout)
at FluentAutomation.SeleniumWebDriver.<>c__DisplayClass2.<Bootstrap>b__0(TinyIoCContainer container)
at FluentAutomation.FluentSession.BootstrapTypeRegistration(Action`1 containerAction)
at FluentAutomation.FluentTest.get_I()
at TestProj.Classes.Browsers.Chrome.Create() in c:\Users\bbdnet0518\Documents\GitHub\vodatest\Classes\Browsers\Chrome.cs:line 18
at TestProj.Classes.Browser..ctor(eBrowser browserType) in c:\Users\bbdnet0518\Documents\GitHub\vodatest\Classes\Browser.cs:line 44
at TestProj.Tests.Basket.Basket.Initialise() in c:\Users\bbdnet0518\Documents\GitHub\vodatest\Tests\Basket\Basket.cs:line 21
]]></stack-trace>
                    </failure>
                    <results>
                      <test-case name="TestProj.Tests.Basket.Basket._01_BasketGridView" description="_01_BasketGridView" executed="True" result="Failure" success="False" time="0.000" asserts="0">
                        <categories>
                          <category name="Basket" />
                        </categories>
                        <properties>
                          <property name="Repeat" value="1" />
                        </properties>
                        <failure>
                          <message><![CDATA[TestFixtureSetUp failed in Basket]]></message>
                          <stack-trace />
                        </failure>
                      </test-case>
                      <test-case name="TestProj.Tests.Basket.Basket._02_BasketConfirmOrder" description="_02_BasketConfirmOrder" executed="True" result="Failure" success="False" time="0.000" asserts="0">
                        <categories>
                          <category name="Basket" />
                        </categories>
                        <properties>
                          <property name="Repeat" value="1" />
                        </properties>
                        <failure>
                          <message><![CDATA[TestFixtureSetUp failed in Basket]]></message>
                          <stack-trace />
                        </failure>
                      </test-case>
                      <test-case name="TestProj.Tests.Basket.Basket._03_BasketListView" description="_03_BasketListView" executed="True" result="Failure" success="False" time="0.000" asserts="0">
                        <categories>
                          <category name="Basket" />
                        </categories>
                        <properties>
                          <property name="Repeat" value="1" />
                        </properties>
                        <failure>
                          <message><![CDATA[TestFixtureSetUp failed in Basket]]></message>
                          <stack-trace />
                        </failure>
                      </test-case>
                      <test-case name="TestProj.Tests.Basket.Basket._04_BasketDetailGridView" description="_04_BasketDetailGridView" executed="True" result="Failure" success="False" time="0.000" asserts="0">
                        <categories>
                          <category name="Basket" />
                        </categories>
                        <properties>
                          <property name="Repeat" value="1" />
                        </properties>
                        <failure>
                          <message><![CDATA[TestFixtureSetUp failed in Basket]]></message>
                          <stack-trace />
                        </failure>
                      </test-case>
                      <test-case name="TestProj.Tests.Basket.Basket._05_BasketDetailListView" description="_05_BasketDetailListView" executed="True" result="Failure" success="False" time="0.000" asserts="0">
                        <categories>
                          <category name="Basket" />
                        </categories>
                        <properties>
                          <property name="Repeat" value="1" />
                        </properties>
                        <failure>
                          <message><![CDATA[TestFixtureSetUp failed in Basket]]></message>
                          <stack-trace />
                        </failure>
                      </test-case>
                      <test-case name="TestProj.Tests.Basket.Basket._06_BasketViewItemDetail" description="_06_BasketViewItemDetail" executed="True" result="Failure" success="False" time="0.000" asserts="0">
                        <categories>
                          <category name="Basket" />
                        </categories>
                        <properties>
                          <property name="Repeat" value="1" />
                        </properties>
                        <failure>
                          <message><![CDATA[TestFixtureSetUp failed in Basket]]></message>
                          <stack-trace />
                        </failure>
                      </test-case>
                      <test-case name="TestProj.Tests.Basket.Basket._07_BasketAddItemToFavourites" description="_07_BasketAddItemToFavourites" executed="True" result="Failure" success="False" time="0.000" asserts="0">
                        <categories>
                          <category name="Basket" />
                        </categories>
                        <properties>
                          <property name="Repeat" value="1" />
                        </properties>
                        <failure>
                          <message><![CDATA[TestFixtureSetUp failed in Basket]]></message>
                          <stack-trace />
                        </failure>
                      </test-case>
                      <test-case name="TestProj.Tests.Basket.Basket._08_BasketAddingAndRemovingProductQuantity" description="_08_BasketAddingAndRemovingProductQuantity" executed="True" result="Failure" success="False" time="0.000" asserts="0">
                        <categories>
                          <category name="Basket" />
                        </categories>
                        <properties>
                          <property name="Repeat" value="1" />
                        </properties>
                        <failure>
                          <message><![CDATA[TestFixtureSetUp failed in Basket]]></message>
                          <stack-trace />
                        </failure>
                      </test-case>
                    </results>
                  </test-suite>
                </results>
              </test-suite>
              <test-suite type="Namespace" name="Catalogues" executed="True" result="Failure" success="False" time="0.088" asserts="0">
                <results>
                  <test-suite type="TestFixture" name="Catalogues" description="Catalogues" executed="True" result="Error" success="False" time="0.086" asserts="0">
                    <categories>
                      <category name="Catalogues" />
                    </categories>
                    <failure>
                      <message><![CDATA[SetUp : System.IO.IOException : The process cannot access the file 'C:\Users\bbdnet0518\AppData\Local\Temp\chromedriver.exe' because it is being used by another process.]]></message>
                      <stack-trace><![CDATA[at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
at System.IO.File.InternalWriteAllBytes(String path, Byte[] bytes, Boolean checkHost)
at FluentAutomation.EmbeddedResources.UnpackFromAssembly(String resourceFileName, String outputFileName, Assembly assembly)
at FluentAutomation.EmbeddedResources.UnpackFromAssembly(String resourceFileName, Assembly assembly)
at FluentAutomation.SeleniumWebDriver.GenerateBrowserSpecificDriver(Browser browser, TimeSpan commandTimeout)
at FluentAutomation.SeleniumWebDriver.<>c__DisplayClass2.<Bootstrap>b__0(TinyIoCContainer container)
at FluentAutomation.FluentSession.BootstrapTypeRegistration(Action`1 containerAction)
at FluentAutomation.FluentTest.get_I()
at TestProj.Classes.Browsers.Chrome.Create() in c:\Users\bbdnet0518\Documents\GitHub\vodatest\Classes\Browsers\Chrome.cs:line 18
at TestProj.Classes.Browser..ctor(eBrowser browserType) in c:\Users\bbdnet0518\Documents\GitHub\vodatest\Classes\Browser.cs:line 44
at TestProj.Tests.Catalogues.Catalogues.Initialise() in c:\Users\bbdnet0518\Documents\GitHub\vodatest\Tests\Catalogues\Catalogues.cs:line 21
]]></stack-trace>
                    </failure>
                    <results>
                      <test-case name="TestProj.Tests.Catalogues.Catalogues._01_SplashInterstialAdvert" description="_01_SplashInterstialAdvert" executed="True" result="Failure" success="False" time="0.000" asserts="0">
                        <categories>
                          <category name="Catalogues" />
                        </categories>
                        <properties>
                          <property name="Repeat" value="1" />
                        </properties>
                        <failure>
                          <message><![CDATA[TestFixtureSetUp failed in Catalogues]]></message>
                          <stack-trace />
                        </failure>
                      </test-case>
                      <test-case name="TestProj.Tests.Catalogues.Catalogues._02_CatalogueLandingPage" description="_02_CatalogueLandingPage" executed="True" result="Failure" success="False" time="0.000" asserts="0">
                        <categories>
                          <category name="Catalogues" />
                        </categories>
                        <properties>
                          <property name="Repeat" value="1" />
                        </properties>
                        <failure>
                          <message><![CDATA[TestFixtureSetUp failed in Catalogues]]></message>
                          <stack-trace />
                        </failure>
                      </test-case>
                      <test-case name="TestProj.Tests.Catalogues.Catalogues._03_CatalogueViewSubMenu" description="_03_CatalogueViewSubMenu" executed="True" result="Failure" success="False" time="0.000" asserts="0">
                        <categories>
                          <category name="Catalogues" />
                        </categories>
                        <properties>
                          <property name="Repeat" value="1" />
                        </properties>
                        <failure>
                          <message><![CDATA[TestFixtureSetUp failed in Catalogues]]></message>
                          <stack-trace />
                        </failure>
                      </test-case>
                      <test-case name="TestProj.Tests.Catalogues.Catalogues._04_CatalogueViewProducts" description="_04_CatalogueViewProducts" executed="True" result="Failure" success="False" time="0.000" asserts="0">
                        <categories>
                          <category name="Catalogues" />
                        </categories>
                        <properties>
                          <property name="Repeat" value="1" />
                        </properties>
                        <failure>
                          <message><![CDATA[TestFixtureSetUp failed in Catalogues]]></message>
                          <stack-trace />
                        </failure>
                      </test-case>
                      <test-case name="TestProj.Tests.Catalogues.Catalogues._05_CatalogueViewProductDetail" description="_05_CatalogueViewProductDetail" executed="True" result="Failure" success="False" time="0.000" asserts="0">
                        <categories>
                          <category name="Catalogues" />
                        </categories>
                        <properties>
                          <property name="Repeat" value="1" />
                        </properties>
                        <failure>
                          <message><![CDATA[TestFixtureSetUp failed in Catalogues]]></message>
                          <stack-trace />
                        </failure>
                      </test-case>
                      <test-case name="TestProj.Tests.Catalogues.Catalogues._06_CatalogueViewAddProductToFavourites" description="_06_CatalogueViewAddProductToFavourites" executed="True" result="Failure" success="False" time="0.000" asserts="0">
                        <categories>
                          <category name="Catalogues" />
                        </categories>
                        <properties>
                          <property name="Repeat" value="1" />
                        </properties>
                        <failure>
                          <message><![CDATA[TestFixtureSetUp failed in Catalogues]]></message>
                          <stack-trace />
                        </failure>
                      </test-case>
                      <test-case name="TestProj.Tests.Catalogues.Catalogues._07_CatalogueViewAddingAndRemovingProductQuantity" description="_07_CatalogueViewAddingAndRemovingProductQuantity" executed="True" result="Failure" success="False" time="0.000" asserts="0">
                        <categories>
                          <category name="Catalogues" />
                        </categories>
                        <properties>
                          <property name="Repeat" value="1" />
                        </properties>
                        <failure>
                          <message><![CDATA[TestFixtureSetUp failed in Catalogues]]></message>
                          <stack-trace />
                        </failure>
                      </test-case>
                    </results>
                  </test-suite>
                </results>
              </test-suite>
              <test-suite type="Namespace" name="ContactUs" executed="True" result="Failure" success="False" time="0.026" asserts="0">
                <results>
                  <test-suite type="TestFixture" name="ContactUs" description="ContactUs" executed="True" result="Error" success="False" time="0.025" asserts="0">
                    <categories>
                      <category name="ContactUs" />
                    </categories>
                    <failure>
                      <message><![CDATA[SetUp : System.IO.IOException : The process cannot access the file 'C:\Users\bbdnet0518\AppData\Local\Temp\chromedriver.exe' because it is being used by another process.]]></message>
                      <stack-trace><![CDATA[at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
at System.IO.File.InternalWriteAllBytes(String path, Byte[] bytes, Boolean checkHost)
at FluentAutomation.EmbeddedResources.UnpackFromAssembly(String resourceFileName, String outputFileName, Assembly assembly)
at FluentAutomation.EmbeddedResources.UnpackFromAssembly(String resourceFileName, Assembly assembly)
at FluentAutomation.SeleniumWebDriver.GenerateBrowserSpecificDriver(Browser browser, TimeSpan commandTimeout)
at FluentAutomation.SeleniumWebDriver.<>c__DisplayClass2.<Bootstrap>b__0(TinyIoCContainer container)
at FluentAutomation.FluentSession.BootstrapTypeRegistration(Action`1 containerAction)
at FluentAutomation.FluentTest.get_I()
at TestProj.Classes.Browsers.Chrome.Create() in c:\Users\bbdnet0518\Documents\GitHub\vodatest\Classes\Browsers\Chrome.cs:line 18
at TestProj.Classes.Browser..ctor(eBrowser browserType) in c:\Users\bbdnet0518\Documents\GitHub\vodatest\Classes\Browser.cs:line 44
at TestProj.Tests.ContactUs.ContactUs.Initialise() in c:\Users\bbdnet0518\Documents\GitHub\vodatest\Tests\ContactUs\ContactUs.cs:line 37
]]></stack-trace>
                    </failure>
                    <results>
                      <test-case name="TestProj.Tests.ContactUs.ContactUs._01_ContactUsTest" description="_01_ContactUs" executed="True" result="Failure" success="False" time="0.000" asserts="0">
                        <categories>
                          <category name="Contact Us" />
                        </categories>
                        <properties>
                          <property name="Repeat" value="1" />
                        </properties>
                        <failure>
                          <message><![CDATA[TestFixtureSetUp failed in ContactUs]]></message>
                          <stack-trace />
                        </failure>
                      </test-case>
                      <test-case name="TestProj.Tests.ContactUs.ContactUs._02_Help" description="_02_Help" executed="True" result="Failure" success="False" time="0.000" asserts="0">
                        <categories>
                          <category name="Alerts" />
                        </categories>
                        <properties>
                          <property name="Repeat" value="1" />
                        </properties>
                        <failure>
                          <message><![CDATA[TestFixtureSetUp failed in ContactUs]]></message>
                          <stack-trace />
                        </failure>
                      </test-case>
                    </results>
                  </test-suite>
                </results>
              </test-suite>
              <test-suite type="Namespace" name="Favourites" executed="True" result="Failure" success="False" time="0.071" asserts="0">
                <results>
                  <test-suite type="TestFixture" name="Favourites" description="Favourites" executed="True" result="Error" success="False" time="0.070" asserts="0">
                    <categories>
                      <category name="Favourites" />
                    </categories>
                    <failure>
                      <message><![CDATA[SetUp : System.IO.IOException : The process cannot access the file 'C:\Users\bbdnet0518\AppData\Local\Temp\chromedriver.exe' because it is being used by another process.]]></message>
                      <stack-trace><![CDATA[at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
at System.IO.File.InternalWriteAllBytes(String path, Byte[] bytes, Boolean checkHost)
at FluentAutomation.EmbeddedResources.UnpackFromAssembly(String resourceFileName, String outputFileName, Assembly assembly)
at FluentAutomation.EmbeddedResources.UnpackFromAssembly(String resourceFileName, Assembly assembly)
at FluentAutomation.SeleniumWebDriver.GenerateBrowserSpecificDriver(Browser browser, TimeSpan commandTimeout)
at FluentAutomation.SeleniumWebDriver.<>c__DisplayClass2.<Bootstrap>b__0(TinyIoCContainer container)
at FluentAutomation.FluentSession.BootstrapTypeRegistration(Action`1 containerAction)
at FluentAutomation.FluentTest.get_I()
at TestProj.Classes.Browsers.Chrome.Create() in c:\Users\bbdnet0518\Documents\GitHub\vodatest\Classes\Browsers\Chrome.cs:line 18
at TestProj.Classes.Browser..ctor(eBrowser browserType) in c:\Users\bbdnet0518\Documents\GitHub\vodatest\Classes\Browser.cs:line 44
at TestProj.Tests.Favourites.Favourites.Initialise() in c:\Users\bbdnet0518\Documents\GitHub\vodatest\Tests\Favourites\Favourites.cs:line 21
]]></stack-trace>
                    </failure>
                    <results>
                      <test-case name="TestProj.Tests.Favourites.Favourites._01_FavouritesInGridView" description="_01_FavouritesInGridView" executed="True" result="Failure" success="False" time="0.000" asserts="0">
                        <categories>
                          <category name="Favourites" />
                        </categories>
                        <properties>
                          <property name="Repeat" value="1" />
                        </properties>
                        <failure>
                          <message><![CDATA[TestFixtureSetUp failed in Favourites]]></message>
                          <stack-trace />
                        </failure>
                      </test-case>
                      <test-case name="TestProj.Tests.Favourites.Favourites._02_FavouritesInListView" description="_02_FavouritesInListView" executed="True" result="Failure" success="False" time="0.000" asserts="0">
                        <categories>
                          <category name="Favourites" />
                        </categories>
                        <properties>
                          <property name="Repeat" value="1" />
                        </properties>
                        <failure>
                          <message><![CDATA[TestFixtureSetUp failed in Favourites]]></message>
                          <stack-trace />
                        </failure>
                      </test-case>
                      <test-case name="TestProj.Tests.Favourites.Favourites._03_FavouritesDetailGridView" description="_03_FavouritesDetailGridView" executed="True" result="Failure" success="False" time="0.000" asserts="0">
                        <categories>
                          <category name="Favourites" />
                        </categories>
                        <properties>
                          <property name="Repeat" value="1" />
                        </properties>
                        <failure>
                          <message><![CDATA[TestFixtureSetUp failed in Favourites]]></message>
                          <stack-trace />
                        </failure>
                      </test-case>
                      <test-case name="TestProj.Tests.Favourites.Favourites._04_FavouritesDetailListView" description="_04_FavouritesDetailListView" executed="True" result="Failure" success="False" time="0.000" asserts="0">
                        <categories>
                          <category name="Favourites" />
                        </categories>
                        <properties>
                          <property name="Repeat" value="1" />
                        </properties>
                        <failure>
                          <message><![CDATA[TestFixtureSetUp failed in Favourites]]></message>
                          <stack-trace />
                        </failure>
                      </test-case>
                      <test-case name="TestProj.Tests.Favourites.Favourites._05_FavouritesViewItemDetail" description="_05_FavouritesViewItemDetail" executed="True" result="Failure" success="False" time="0.000" asserts="0">
                        <categories>
                          <category name="Favourites" />
                        </categories>
                        <properties>
                          <property name="Repeat" value="1" />
                        </properties>
                        <failure>
                          <message><![CDATA[TestFixtureSetUp failed in Favourites]]></message>
                          <stack-trace />
                        </failure>
                      </test-case>
                      <test-case name="TestProj.Tests.Favourites.Favourites._06_FavouritesAddItemToFavourites" description="_06_FavouritesAddItemToFavourites" executed="True" result="Failure" success="False" time="0.000" asserts="0">
                        <categories>
                          <category name="Basket" />
                        </categories>
                        <properties>
                          <property name="Repeat" value="1" />
                        </properties>
                        <failure>
                          <message><![CDATA[TestFixtureSetUp failed in Favourites]]></message>
                          <stack-trace />
                        </failure>
                      </test-case>
                      <test-case name="TestProj.Tests.Favourites.Favourites._07_FavouritesAddingAndRemovingProductQuantity" description="_07_FavouritesAddingAndRemovingProductQuantity" executed="True" result="Failure" success="False" time="0.000" asserts="0">
                        <categories>
                          <category name="Basket" />
                        </categories>
                        <properties>
                          <property name="Repeat" value="1" />
                        </properties>
                        <failure>
                          <message><![CDATA[TestFixtureSetUp failed in Favourites]]></message>
                          <stack-trace />
                        </failure>
                      </test-case>
                    </results>
                  </test-suite>
                </results>
              </test-suite>
              <test-suite type="Namespace" name="GeneralApplicationNavigation" executed="True" result="Failure" success="False" time="0.040" asserts="0">
                <results>
                  <test-suite type="TestFixture" name="GeneralApplicationNavigation" description="GeneralApplicationNavigation" executed="True" result="Error" success="False" time="0.038" asserts="0">
                    <categories>
                      <category name="GeneralApplicationNavigation" />
                    </categories>
                    <failure>
                      <message><![CDATA[SetUp : System.IO.IOException : The process cannot access the file 'C:\Users\bbdnet0518\AppData\Local\Temp\chromedriver.exe' because it is being used by another process.]]></message>
                      <stack-trace><![CDATA[at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
at System.IO.File.InternalWriteAllBytes(String path, Byte[] bytes, Boolean checkHost)
at FluentAutomation.EmbeddedResources.UnpackFromAssembly(String resourceFileName, String outputFileName, Assembly assembly)
at FluentAutomation.EmbeddedResources.UnpackFromAssembly(String resourceFileName, Assembly assembly)
at FluentAutomation.SeleniumWebDriver.GenerateBrowserSpecificDriver(Browser browser, TimeSpan commandTimeout)
at FluentAutomation.SeleniumWebDriver.<>c__DisplayClass2.<Bootstrap>b__0(TinyIoCContainer container)
at FluentAutomation.FluentSession.BootstrapTypeRegistration(Action`1 containerAction)
at FluentAutomation.FluentTest.get_I()
at TestProj.Classes.Browsers.Chrome.Create() in c:\Users\bbdnet0518\Documents\GitHub\vodatest\Classes\Browsers\Chrome.cs:line 18
at TestProj.Classes.Browser..ctor(eBrowser browserType) in c:\Users\bbdnet0518\Documents\GitHub\vodatest\Classes\Browser.cs:line 44
at TestProj.Tests.GeneralApplicationNavigation.GeneralApplicationNavigation.Initialise() in c:\Users\bbdnet0518\Documents\GitHub\vodatest\Tests\GeneralApplicationNavigation\GeneralApplicationNavigation.cs:line 21
]]></stack-trace>
                    </failure>
                    <results>
                      <test-case name="TestProj.Tests.GeneralApplicationNavigation.GeneralApplicationNavigation._01_SearchFieldValidations" description="_01_SearchFieldValidations" executed="True" result="Failure" success="False" time="0.000" asserts="0">
                        <categories>
                          <category name="Search" />
                        </categories>
                        <properties>
                          <property name="Repeat" value="1" />
                        </properties>
                        <failure>
                          <message><![CDATA[TestFixtureSetUp failed in GeneralApplicationNavigation]]></message>
                          <stack-trace />
                        </failure>
                      </test-case>
                      <test-case name="TestProj.Tests.GeneralApplicationNavigation.GeneralApplicationNavigation._02_GridviewSearchOfflineOnline" description="_02_GridviewSearchOfflineOnline" executed="True" result="Failure" success="False" time="0.000" asserts="0">
                        <categories>
                          <category name="Search" />
                        </categories>
                        <properties>
                          <property name="Repeat" value="1" />
                        </properties>
                        <failure>
                          <message><![CDATA[TestFixtureSetUp failed in GeneralApplicationNavigation]]></message>
                          <stack-trace />
                        </failure>
                      </test-case>
                      <test-case name="TestProj.Tests.GeneralApplicationNavigation.GeneralApplicationNavigation._03_ListViewSearchOfflineOnline" description="_03_ListViewSearchOfflineOnline" executed="True" result="Failure" success="False" time="0.000" asserts="0">
                        <categories>
                          <category name="Search" />
                        </categories>
                        <properties>
                          <property name="Repeat" value="1" />
                        </properties>
                        <failure>
                          <message><![CDATA[TestFixtureSetUp failed in GeneralApplicationNavigation]]></message>
                          <stack-trace />
                        </failure>
                      </test-case>
                    </results>
                  </test-suite>
                </results>
              </test-suite>
              <test-suite type="Namespace" name="Orders" executed="True" result="Failure" success="False" time="0.100" asserts="0">
                <results>
                  <test-suite type="TestFixture" name="Orders" description="Orders" executed="True" result="Error" success="False" time="0.098" asserts="0">
                    <categories>
                      <category name="Orders" />
                    </categories>
                    <failure>
                      <message><![CDATA[SetUp : System.IO.IOException : The process cannot access the file 'C:\Users\bbdnet0518\AppData\Local\Temp\chromedriver.exe' because it is being used by another process.]]></message>
                      <stack-trace><![CDATA[at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
at System.IO.File.InternalWriteAllBytes(String path, Byte[] bytes, Boolean checkHost)
at FluentAutomation.EmbeddedResources.UnpackFromAssembly(String resourceFileName, String outputFileName, Assembly assembly)
at FluentAutomation.EmbeddedResources.UnpackFromAssembly(String resourceFileName, Assembly assembly)
at FluentAutomation.SeleniumWebDriver.GenerateBrowserSpecificDriver(Browser browser, TimeSpan commandTimeout)
at FluentAutomation.SeleniumWebDriver.<>c__DisplayClass2.<Bootstrap>b__0(TinyIoCContainer container)
at FluentAutomation.FluentSession.BootstrapTypeRegistration(Action`1 containerAction)
at FluentAutomation.FluentTest.get_I()
at TestProj.Classes.Browsers.Chrome.Create() in c:\Users\bbdnet0518\Documents\GitHub\vodatest\Classes\Browsers\Chrome.cs:line 18
at TestProj.Classes.Browser..ctor(eBrowser browserType) in c:\Users\bbdnet0518\Documents\GitHub\vodatest\Classes\Browser.cs:line 44
at TestProj.Tests.Orders.Orders.Initialise() in c:\Users\bbdnet0518\Documents\GitHub\vodatest\Tests\Orders\Orders.cs:line 21
]]></stack-trace>
                    </failure>
                    <results>
                      <test-case name="TestProj.Tests.Orders.Orders._01_PendingOrdersConfirmation" description="_01_PendingOrdersConfirmation" executed="True" result="Failure" success="False" time="0.000" asserts="0">
                        <categories>
                          <category name="Orders" />
                        </categories>
                        <properties>
                          <property name="Repeat" value="1" />
                        </properties>
                        <failure>
                          <message><![CDATA[TestFixtureSetUp failed in Orders]]></message>
                          <stack-trace />
                        </failure>
                      </test-case>
                      <test-case name="TestProj.Tests.Orders.Orders._02_ViewConfirmedOrder" description="_02_ViewConfirmedOrder" executed="True" result="Failure" success="False" time="0.000" asserts="0">
                        <categories>
                          <category name="Orders" />
                        </categories>
                        <properties>
                          <property name="Repeat" value="1" />
                        </properties>
                        <failure>
                          <message><![CDATA[TestFixtureSetUp failed in Orders]]></message>
                          <stack-trace />
                        </failure>
                      </test-case>
                      <test-case name="TestProj.Tests.Orders.Orders._03_OrderHistoryCollapsedView" description="_03_OrderHistoryCollapsedView" executed="True" result="Failure" success="False" time="0.000" asserts="0">
                        <categories>
                          <category name="Orders" />
                        </categories>
                        <properties>
                          <property name="Repeat" value="1" />
                        </properties>
                        <failure>
                          <message><![CDATA[TestFixtureSetUp failed in Orders]]></message>
                          <stack-trace />
                        </failure>
                      </test-case>
                      <test-case name="TestProj.Tests.Orders.Orders._04_OrderHistoryExpanded" description="_04_OrderHistoryExpanded" executed="True" result="Failure" success="False" time="0.000" asserts="0">
                        <categories>
                          <category name="Orders" />
                        </categories>
                        <properties>
                          <property name="Repeat" value="1" />
                        </properties>
                        <failure>
                          <message><![CDATA[TestFixtureSetUp failed in Orders]]></message>
                          <stack-trace />
                        </failure>
                      </test-case>
                      <test-case name="TestProj.Tests.Orders.Orders._05_ViewInvoiceDetail" description="_05_ViewInvoiceDetail" executed="True" result="Failure" success="False" time="0.000" asserts="0">
                        <categories>
                          <category name="Orders" />
                        </categories>
                        <properties>
                          <property name="Repeat" value="1" />
                        </properties>
                        <failure>
                          <message><![CDATA[TestFixtureSetUp failed in Orders]]></message>
                          <stack-trace />
                        </failure>
                      </test-case>
                      <test-case name="TestProj.Tests.Orders.Orders._06_ViewOrderDetails" description="_06_ViewOrderDetails" executed="True" result="Failure" success="False" time="0.000" asserts="0">
                        <categories>
                          <category name="Orders" />
                        </categories>
                        <properties>
                          <property name="Repeat" value="1" />
                        </properties>
                        <failure>
                          <message><![CDATA[TestFixtureSetUp failed in Orders]]></message>
                          <stack-trace />
                        </failure>
                      </test-case>
                      <test-case name="TestProj.Tests.Orders.Orders._07_eOrder" description="_07_ReOrder" executed="True" result="Failure" success="False" time="0.000" asserts="0">
                        <categories>
                          <category name="Orders" />
                        </categories>
                        <properties>
                          <property name="Repeat" value="1" />
                        </properties>
                        <failure>
                          <message><![CDATA[TestFixtureSetUp failed in Orders]]></message>
                          <stack-trace />
                        </failure>
                      </test-case>
                      <test-case name="TestProj.Tests.Orders.Orders._08_UnconfirmedOrders" description="_08_UnconfirmedOrders" executed="True" result="Failure" success="False" time="0.000" asserts="0">
                        <categories>
                          <category name="Orders" />
                        </categories>
                        <properties>
                          <property name="Repeat" value="1" />
                        </properties>
                        <failure>
                          <message><![CDATA[TestFixtureSetUp failed in Orders]]></message>
                          <stack-trace />
                        </failure>
                      </test-case>
                      <test-case name="TestProj.Tests.Orders.Orders._09_ViewInvoices" description="_09_ViewInvoices" executed="True" result="Failure" success="False" time="0.000" asserts="0">
                        <categories>
                          <category name="Orders" />
                        </categories>
                        <properties>
                          <property name="Repeat" value="1" />
                        </properties>
                        <failure>
                          <message><![CDATA[TestFixtureSetUp failed in Orders]]></message>
                          <stack-trace />
                        </failure>
                      </test-case>
                      <test-case name="TestProj.Tests.Orders.Orders._10_LoggingDiscrepancies" description="_10_LoggingDiscrepancies" executed="True" result="Failure" success="False" time="0.000" asserts="0">
                        <categories>
                          <category name="Orders" />
                        </categories>
                        <properties>
                          <property name="Repeat" value="1" />
                        </properties>
                        <failure>
                          <message><![CDATA[TestFixtureSetUp failed in Orders]]></message>
                          <stack-trace />
                        </failure>
                      </test-case>
                    </results>
                  </test-suite>
                </results>
              </test-suite>
            </results>
          </test-suite>
        </results>
      </test-suite>
    </results>
  </test-suite>
</test-results>